### ISSUE TITLE
Kubernetes Checklist

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/Infrastructure#8]
- [x] Figure out if we want to use Cloudflare or just proxy through master node
- [x] Make control plane on Site A stable
- [x] Add worker nodes to Site A
- [x] Test failover
- [ ] Figure out redundancy plan for OpenVPN
- [x] Add support for Ingress, ensure our deployment of `refresh-gopherfrontend` is stable
- [ ] #7
- [x] Fix NGINX ingress controller deploying internal Kubernetes TLS certificates
